name: Linux build & test
description: 'Build and test ToulBar2 on Linux platform'

inputs:
  build_type:
    default: 'Release'
  libtb2:
    default: 'ON'
  pytb2:
    default: 'ON'

runs:
  using: "composite"
  steps:

    - name: install dependencies

      shell: bash
      run: sudo apt install libboost-all-dev libgmp-dev zlib1g-dev liblzma-dev libjemalloc-dev libopenmpi-dev openmpi-bin libeigen3-dev

    - name: test
      env:
        PYTB2: ${{ inputs.pytb2 }}
      shell: bash
      # pytoulbar2 dependencies  
      if: ${{ inputs.pytb2 == 'ON' }}
      run: pip install pybind11[global]

    - uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{runner.workspace}}/toulbar2/build

    - name: Configure CMake
      env:
        BUILD_TYPE: ${{ inputs.build_type }}
        LIBTB2: ${{ inputs.libtb2 }}
        PYTB2: ${{ inputs.pytb2 }}
      shell: bash
      working-directory: ${{runner.workspace}}/toulbar2/build
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBTB2=$LIBDTB2 -DPYTB2=$PYTB2 ..

    - name: Build ToulBar2
      working-directory: ${{runner.workspace}}/toulbar2/build
      shell: bash
      run: make -j 4
  
    - name: Run Test
      working-directory: ${{runner.workspace}}/toulbar2/build
      shell: bash
      run: make test -j 4
