name: Windows build & test
description: 'Build and test ToulBar2 on Linux platform'

inputs:
  build_type:
    default: 'Release'
  run_tests:
    default: false
  make_package:
    default: false
  libtb2:
    default: 'ON'
  pytb2:
    default: 'ON'
  mpi:
    default: 'OFF'
  boost:
    default: 'ON'
  xml:
    default: 'ON'

runs:
  using: "composite"
  steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-ucrt-x86_64-gcc ucrt64/mingw-w64-ucrt-x86_64-cmake ucrt64/mingw-w64-ucrt-x86_64-pybind11 ucrt64/mingw-w64-ucrt-x86_64-boost ucrt64/mingw-w64-ucrt-x86_64-bc ucrt64/mingw-w64-ucrt-x86_64-eigen3

    - name: Create Build Environment
      shell: msys2 {0}
      run: cmake -E make_directory "${{runner.workspace}}/toulbar2/build"

    - name: Configure CMake
      env:
        BUILD_TYPE: ${{ inputs.build_type }}
        LIBTB2: ${{ inputs.libtb2 }}
        PYTB2: ${{ inputs.pytb2 }}
        MPI: ${{ inputs.mpi }}
        BOOST: ${{ inputs.boost }}
        XML: ${{ inputs.xml }}
      shell: msys2 {0}
      working-directory: "${{runner.workspace}}/toulbar2/build"
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBoost=$BOOST -DLIBTB2=$LIBDTB2 -DMPI=$MPI -DPYTB2=$PYTB2 -DXML=$XML ..

    - name: Build ToulBar2
      shell: msys2 {0}
      working-directory: "${{runner.workspace}}/toulbar2/build"
      run: cmake --build . --verbose

    - name: Test ls
      shell: msys2 {0}
      working-directory: "${{runner.workspace}}/toulbar2/build"
      if: ${{ inputs.run_tests == 'true' }}
      run: ls pytoulbar2 

    - name: Run Tests
      shell: msys2 {0}
      working-directory: "${{runner.workspace}}/toulbar2/build"
      if: ${{ inputs.run_tests == 'true' }}
      # run: ctest .
      run: ctest . -R validation_pytb2_bilevel/bilevel_mibs0.py --verbose

    - name: Make Packages
      shell: msys2 {0}
      working-directory: ${{runner.workspace}}/toulbar2/build
      if: ${{ inputs.make_package == 'true' }}
      run: cpack --config CPackConfig.cmake

    - name: Test package files
      working-directory: ${{runner.workspace}}/toulbar2/build
      shell: msys2 {0}
      if: ${{ inputs.make_package == 'true' }}
      run: ls
