name: "docs-deploy toulbar2 site on GitHub Pages v2"

# workflow manually executed
on:
  workflow_dispatch:
jobs:

  build-and-deploy-docs:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: "Cache"
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "ToulBar2 docs build"
        image: ghcr.io/toulbar2/toulbar2/toulbar2_docs
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.toulbar2_docs_pull }}
        volumes:
          - ./:/docs

      - name: "Deploy on Github Pages (ghp-import)"
        run: | 
          ghp-import -n -p -f docs/_build/html

