name: Manual build macos
on:
  workflow_dispatch:

jobs:

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: macos build test
        uses: ./.github/actions/macos_build
        with:
          pytb2: 'OFF'