name: Manual build windows
on:
  workflow_dispatch:

jobs:

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Windows build test
        uses: ./.github/actions/windows_build
        with:
          pytb2: 'OFF'