name: Multiple builds test

on:
  workflow_dispatch:

jobs:

  toulbar2-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  windows-build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      # - uses: actions/checkout@v4

      - name: Windows build
        uses: ./.github/actions/windows_build
        with:
          pytb2: 'OFF'

  # macos-build:

  linux-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # - uses: actions/checkout@v4

      - name: Linux build
        uses: ./.github/actions/linux_build
        with:
          pytb2: 'OFF'
          mpi: 'OFF'

  

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "release.tar.gz,foo/*.txt"
      #     bodyFile: "body.md"
  
  post_build:
    runs-on: ubuntu-latest
  
    steps:

      - name: test
        shell: bash
        run: ls ${{runner.workspace}}/toulbar2/build/lib