name: Multiple builds test

on:
  workflow_dispatch:

jobs:

  windows-build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      - name: Windows build
        uses: ./.github/actions/windows_build
        with:
          pytb2: 'OFF'

      - uses: actions/upload-artifact@v4
        with:
          name: toulbar2_windows
          path: |
            ${{runner.workspace}}/toulbar2/build/lib
            ${{runner.workspace}}/toulbar2/build/bin 
          retention-days: 1

  # macos-build:

  linux-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      - name: Linux build
        uses: ./.github/actions/linux_build
        with:
          pytb2: 'OFF'
          mpi: 'OFF'

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "release.tar.gz,foo/*.txt"
      #     bodyFile: "body.md"

      - uses: actions/upload-artifact@v4
        with:
          name: toulbar2_linux
          path: |
            ${{runner.workspace}}/toulbar2/build/lib
            ${{runner.workspace}}/toulbar2/build/bin
          retention-days: 1
  

  # post_build:
  #   runs-on: ubuntu-latest
  #   needs: [windows-build, linux-build]

  #   steps:

  #     - name: test
  #       shell: bash
  #       run: ls ${{runner.workspace}}/toulbar2/build/lib