name: Push build & test
on:
  push: # check Linux build and test on push
    branches:
      - 'ci-cd'

jobs:

  push_test:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v4
      - name: Build on push
        uses: .github/actions/linux_build
        with:
          pytb2: 'OFF'