name: CI
on:
  # push: # check Linux build and test on push
  #   branches:
  #     - 'ci-cd'
  workflow_dispatch:

jobs:

  push_test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/cache/restore@v4
        id: toulbar2-push-cache-restore
        with:
          path: ${{runner.workspace}}/toulbar2
          key: toulbar2_ci

      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Build on push
        uses: ./.github/actions/linux_build
        with:
          pytb2: 'ON'
          mpi: 'OFF'
          XML: 'OFF' # temporary
          run_tests: true


      # delete previous cache
      - name: Cleanup cache
        env:
          GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
        if: steps.toulbar2-push-cache-restore.outputs.cache-hit == 'true'
        run: gh cache delete toulbar2_ci

      # caching last version for next ci-build
      - uses: actions/cache/save@v4
        id: toulbar2-push-cache-save
        with:
          path: ${{runner.workspace}}/toulbar2
          key: toulbar2_ci