name: CI
on:
  push: # check Linux build and test on push
    branches:
      - 'ci-cd'
  # workflow_dispatch:

jobs:

  push_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build on push
        uses: ./.github/actions/linux_build
        with:
          pytb2: 'ON'
          mpi: 'OFF'
          run_tests: true