name: pytoulbar2

on:
  workflow_dispatch:

jobs:



  pytb2-linux:
    if: false
    name: pytoulbar2-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_BEFORE_BUILD: "yum -y install gmp-devel boost169-devel zlib-devel bzip2-devel xz-devel libxml2-devel eigen3-devel && pip install -r dev-requirements.txt"
          CIBW_ENVIRONMENT: BOOST_INCLUDEDIR=/usr/include/boost169 BOOST_LIBRARYDIR=/usr/lib64/boost169
          
          CIBW_BUILD: "cp36-*"
          # CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"

          CIBW_SKIP: "*-manylinux_i686* *-musllinux*"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_TEST: "python3 -c \"from distutils import util; print(util.get_platform())\" && pip install pytest"
          CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && pytest ./tests"





  pytb2-macos-intel:
    if: false
    name: pytoulbar2-macos-intel
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.9 HOMEBREW_NO_AUTO_UPDATE=1

          CIBW_PROJECT_REQUIRES_PYTHON: "<=3.6.8"

          # with cpython 3.7, the min macos version cannot be 10.9

          CIBW_BEFORE_BUILD: "softwareupdate --list && softwareupdate -i \"Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1\" && brew install cmake gmp zlib xz boost eigen && pip install -r dev-requirements.txt && python3 -c \"from distutils import util; print(util.get_platform())\" && python -sSc 'import platform; print(platform.machine())'"
          HOMEBREW_NO_AUTO_UPDATE: 1

          # CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"
          
          CIBW_BUILD: "cp37-*"

          CIBW_BUILD_VERBOSITY: 1

          CIBW_REPAIR_WHEEL_COMMAND: "delocate-listdeps --all {wheel} && export MACOSX_DEPLOYMENT_TARGET=13 && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

          # CIBW_REPAIR_WHEEL_COMMAND: "bash {package}/travis/repair_mac_wheels.sh {wheel}"

          CIBW_BEFORE_TEST: "pip install pytest"

          CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && pytest ./tests"




  pytb2-macos-arm:
    if: false
    name: pytoulbar2-macos-arm
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=14.0 CMAKE_APPLE_SILICON_PROCESSOR=arm64
          CIBW_BEFORE_BUILD: "brew install cmake gmp zlib xz boost eigen && pip install -r dev-requirements.txt"
          HOMEBREW_NO_AUTO_UPDATE: 1
          
          # starts from cpython 3.9
          # CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"
          CIBW_BUILD: "cp37-*"

          CIBW_BUILD_VERBOSITY: 1

          CIBW_BEFORE_TEST: "python3 -c \"from distutils import util; print(util.get_platform())\" && pip install pytest"
          CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && pytest ./tests"



  # pytb2-windows:
  #   # if: false
  #   name: pytoulbar2-windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.23.0
  #       env:

  #         CIBW_BEFORE_BUILD: "choco install boost-msvc-14.2 -f -y && pip install pybind11[global]"
          
  #         HOMEBREW_NO_AUTO_UPDATE: 1
          
  #         # CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"
  #         CIBW_BUILD: "cp36-*"

  #         CIBW_BUILD_VERBOSITY: 1

  #         # CIBW_BEFORE_TEST: "python3 -c \"from distutils import util; print(util.get_platform())\" && pip install pytest"
  #         # CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && pytest ./tests"


  pytb2-windows:

    name: pytoulbar2-windows
    
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc ucrt64/mingw-w64-ucrt-x86_64-cmake python python-pip ucrt64/mingw-w64-ucrt-x86_64-pybind11 ucrt64/mingw-w64-ucrt-x86_64-boost ucrt64/mingw-w64-ucrt-x86_64-bc ucrt64/mingw-w64-ucrt-x86_64-eigen3

      - name: build
        shell: msys2 {0}
        run: "pip3 wheel ./ --no-deps -w wheelhouse"