name: pytoulbar2

on:
  workflow_dispatch:

jobs:

  pytb2-linux:
    
    name: pytoulbar2-linux
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_BEFORE_BUILD: "yum -y install gmp-devel boost169-devel zlib-devel bzip2-devel xz-devel libxml2-devel eigen3-devel && pip install -r dev-requirements.txt && cmake --version"
          CIBW_ENVIRONMENT: BOOST_INCLUDEDIR=/usr/include/boost169 BOOST_LIBRARYDIR=/usr/lib64/boost169
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"
          # CIBW_SKIP: "*-manylinux*"
          CIBW_BUILD_VERBOSITY: 1
          # CIBW_REPAIR_WHEEL_COMMAND: "bash ./travis/repair_linux_wheels.sh wheelhouse"
          
          
          #   CIBW_SOME_OPTION: value
          # - python3 -m cibuildwheel --output-dir wheelhouse
          # - ls wheelhouse/
          # - bash ./travis/repair_mac_wheels.sh wheelhouse