name: pytoulbar2

on:
  workflow_dispatch:

jobs:

  pytoulbar2-linux:
    
    name: pytoulbar2-linux
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_BEFORE_BUILD: "pip install -r dev-requirements.txt"
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"
          # CIBW_SKIP: "*-manylinux*"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_REPAIR_WHEEL_COMMAND: "bash ./travis/repair_mac_wheels.sh wheelhouse"
          
          
          #   CIBW_SOME_OPTION: value
          # - python3 -m cibuildwheel --output-dir wheelhouse
          # - ls wheelhouse/
          # - bash ./travis/repair_mac_wheels.sh wheelhouse