name: release_pytb2

on:

  release:
    types: [published]
  
  # workflow_dispatch:

jobs:

  pytb2-release:
    name: pytoulbar2-release
    runs-on: ubuntu-latest
    steps:

       - uses: actions/checkout@v4

       - name: update ptb2 version
         run: |
           cat ${{runner.workspace}}/toulbar2_ci/setup.py
           sed -i "s/version=.*/version=\"0.0.0.6\" # hash $(git rev-parse HEAD) /" setup.py
           cat ${{runner.workspace}}/toulbar2_ci/setup.py
           git config --global user.name 'smbct'
           git config --global user.email 'smbct@users.noreply.github.com'
           git commit -am "[auto] update pytb2 version tag"
           git push origin HEAD