name: Releases

on:
  workflow_dispatch:

# on: 
#   push:
#     tags:
#     - '*'

jobs:

  # windows-build:
  #   runs-on: windows-latest
  #   permissions:
  #     contents: write
    
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Windows build
  #       uses: ./.github/actions/windows_build
  #       with:
  #         pytb2: 'OFF'

  # macos-build:

  linux-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Linux build
        uses: ./.github/actions/linux_build
        with:
          xml: 'OFF'
          make_package: true

      # upload linux binaries artifact
      - uses: actions/upload-artifact@v4
        with:
          name: toulbar2_linux
          path: |
            ${{runner.workspace}}/toulbar2/build/*.tar.gz
            ${{runner.workspace}}/toulbar2/build/*.deb
            ${{runner.workspace}}/toulbar2/build/*.rpm
          retention-days: 1

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "release.tar.gz,foo/*.txt"
      #     bodyFile: "body.md"
  