name: release_pytb2

on:

  release:
    types: [published]
  
  # workflow_dispatch:

jobs:

  pytb2-release:
    name: pytoulbar2-release
    runs-on: ubuntu-latest
    steps:

       - uses: actions/checkout@v4
         with:
           ref: 'ci-cd'

       - name: update ptb2 version
         run: |
           echo "Release name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"
           pytb2_version=$(echo ${{ github.event.release.body }}| grep -oP "(?<=pytoulbar2=).*")
           echo "new pytb2 version: $pytb2_version"
           sed -i "s/version=.*/version=\"$pytb2_version\" # hash $(git rev-parse HEAD) /" setup.py
        
       - name: push changes
           git config --global user.name 'smbct'
           git config --global user.email 'smbct@users.noreply.github.com'
           git commit -am "[auto] update pytb2 version tag"
           git push