name: Test linux
on:
  workflow_dispatch:
    inputs:
      
      build_type:
        type: choice
        description: "Build type : debug or Release"
        options: 
        - Release
        - Debug
      
      libtoulbar2:
        type: boolean
        description: "Compile ToulBar2 C++ library"

      pytoulbar2:
        type: boolean
        description: "Compile pytoulbar2"

      run_tests:
        type: boolean
        description: "Run unit tests with CMake"

jobs:

  test_linux:
    runs-on: ubuntu-latest
    env:
        LIBTB2: 'OFF'
        PYTB2: 'OFF'
    steps:

      - uses: actions/checkout@v4

      - name: Set LIBTB2 env var
        run: |
          if [[ ${{ inputs.libtoulbar2 == 'true' }}  ]]; then
              echo "LIBTB2=ON" >> "$GITHUB_ENV"
          fi

      - name: Set PYTB2 env var
        run: |
          if [[ ${{ inputs.pytoulbar2 == 'true' }}  ]]; then
              echo "PYTB2=ON" >> "$GITHUB_ENV"
          fi

      # - name: Set PYTB2 env var

      - name: Linux build test
        uses: ./.github/actions/linux_build
        with:
          pytb2: ${{env.PYTB2}}
          libtb2: ${{env.LIBTB2}}
          build_type: ${{ github.event.inputs.build_type }}
          run_test: ${{ github.event.inputs.run_tests }}