name: Test linux
on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: "Build type : debug or Release"
        options: 
        - Debug
        - Release
      run_tests:
        type: boolean
        description: "Run unit tests with CMake"

jobs:

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linux build test
        uses: ./.github/actions/linux_build
        with:
          pytb2: 'ON'
          build_type: ${{ github.event.inputs.build_type }}
          run_test: ${{ github.event.inputs.run_tests }}