name: Windows build_test
on:
  workflow_dispatch:

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc ucrt64/mingw-w64-ucrt-x86_64-cmake ucrt64/mingw-w64-ucrt-x86_64-pybind11 ucrt64/mingw-w64-ucrt-x86_64-boost ucrt64/mingw-w64-ucrt-x86_64-bc ucrt64/mingw-w64-ucrt-x86_64-eigen3

      - name: Create Build Environment
        run: cmake -E make_directory "${{runner.workspace}}/toulbar2/build"

      - name: Configure CMake
        working-directory: "${{runner.workspace}}/toulbar2/build"
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBT2B=ON ..


      - name: Build ToulBar2
        working-directory: "${{runner.workspace}}/toulbar2/build"
        shell: bash
        run: cmake --build .
  
      - name: Run Test
        working-directory: "${{runner.workspace}}/toulbar2/build"
        shell: bash
        run: ctest .